"""empty message

Revision ID: 14f49f749e85
Revises: 88e637517b49
Create Date: 2019-07-14 03:21:22.248025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f49f749e85'
down_revision = '88e637517b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dutyevent', 'table_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dutyevent', 'table_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
