"""empty message

Revision ID: 1a7de2d59bd2
Revises: 54420316811e
Create Date: 2019-07-14 02:56:50.563777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7de2d59bd2'
down_revision = '54420316811e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dutyevent', ['table_date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dutyevent', type_='unique')
    # ### end Alembic commands ###
