"""empty message

Revision ID: 35ac2a786055
Revises: 77c55aa1cd3d
Create Date: 2019-07-19 16:20:05.997171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ac2a786055'
down_revision = '77c55aa1cd3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dutyevent', sa.Column('duty_person', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dutyevent', 'duty_person')
    # ### end Alembic commands ###
