"""add email

Revision ID: 3b5ea2ee2338
Revises: e7059680acd6
Create Date: 2019-07-02 22:52:51.619148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5ea2ee2338'
down_revision = 'e7059680acd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'email')
    # ### end Alembic commands ###
