"""empty message

Revision ID: 51a3a0338e3b
Revises: 9a8674d5fc83
Create Date: 2019-07-05 01:50:27.234997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a3a0338e3b'
down_revision = '9a8674d5fc83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dutyevent', sa.Column('table_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dutyevent', 'table_date')
    # ### end Alembic commands ###
