"""first migrate

Revision ID: 771fbe549654
Revises: 
Create Date: 2019-06-23 16:43:45.320883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771fbe549654'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dutyevent_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duty_type_id', sa.Integer(), nullable=True),
    sa.Column('duty_person_id', sa.Integer(), nullable=True),
    sa.Column('date_time_start', sa.DateTime(), nullable=False),
    sa.Column('date_time_stop', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['duty_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['duty_type_id'], ['dutytype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dutyevent_test')
    # ### end Alembic commands ###
