"""first migrate

Revision ID: 846b0d7094cc
Revises: 771fbe549654
Create Date: 2019-06-23 16:44:35.374572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846b0d7094cc'
down_revision = '771fbe549654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dutyevent_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dutyevent_test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('duty_type_id', sa.INTEGER(), nullable=True),
    sa.Column('duty_person_id', sa.INTEGER(), nullable=True),
    sa.Column('date_time_start', sa.DATETIME(), nullable=False),
    sa.Column('date_time_stop', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['duty_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['duty_type_id'], ['dutytype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
