"""empty message

Revision ID: 88e637517b49
Revises: 54420316811e
Create Date: 2019-07-14 03:20:57.047441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e637517b49'
down_revision = '54420316811e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dutyevent', 'table_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dutyevent', 'table_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
