"""1 commit

Revision ID: 9b6daa731370
Revises: 
Create Date: 2019-06-23 21:35:54.416009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b6daa731370'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dutyevent2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dutyevent2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('duty_type_id', sa.INTEGER(), nullable=True),
    sa.Column('duty_person_id', sa.INTEGER(), nullable=True),
    sa.Column('date_time_start', sa.DATETIME(), nullable=False),
    sa.Column('date_time_stop', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['duty_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['duty_type_id'], ['dutytype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
