"""empty message

Revision ID: d2ddcccf9741
Revises: 51a3a0338e3b
Create Date: 2019-07-12 03:04:40.096515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ddcccf9741'
down_revision = '51a3a0338e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('name2', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'name2')
    # ### end Alembic commands ###
