"""add db

Revision ID: e7059680acd6
Revises: 
Create Date: 2019-07-02 22:42:47.281345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7059680acd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_role'), 'person', ['role'], unique=False)
    op.create_index(op.f('ix_person_username'), 'person', ['username'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeinterval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=False),
    sa.Column('time_end', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dutytype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('time_interval_id', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['time_interval_id'], ['timeinterval.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roleperson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dutyevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duty_type_id', sa.Integer(), nullable=True),
    sa.Column('duty_person_id', sa.Integer(), nullable=True),
    sa.Column('date_time_start', sa.DateTime(), nullable=False),
    sa.Column('date_time_stop', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['duty_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['duty_type_id'], ['dutytype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dutyevent')
    op.drop_table('roleperson')
    op.drop_table('dutytype')
    op.drop_table('timeinterval')
    op.drop_table('role')
    op.drop_index(op.f('ix_person_username'), table_name='person')
    op.drop_index(op.f('ix_person_role'), table_name='person')
    op.drop_table('person')
    # ### end Alembic commands ###
