"""empty message

Revision ID: f7e7721f6d65
Revises: d3492f50e938
Create Date: 2019-07-17 00:32:23.571608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e7721f6d65'
down_revision = 'd3492f50e938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeinterval', sa.Column('time_end2', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeinterval', 'time_end2')
    # ### end Alembic commands ###
